### ISSUE TITLE
소셜 로그인

### ISSUE THREAD

**Issue by pym7857** [pym7857/meeting_app_flutter#1]
- [x] 구글 로그인: Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
- [x] 페이스북 로그인:  구현 완료
- [x] 카카오 로그인: Access 코드가 안넘어옴
- [x] 네이버 로그인: 시작 안됨

**Comment by dkalshek** [comment]
구글 로그인 : 버전 문제(해결)

**Comment by dkalshek** [comment]
이슈 해결
